apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::060399601368:role/eks-project-eu-west-1-sandbox-portfolio-ecr-role
