apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::060399601368:role/eks-project-eu-west-1-sandbox-cert-manager-role
